### ISSUE TITLE
Suggestion: Update package scrpage2 to scrlayer-scrpage

### ISSUE THREAD

**Issue by pomcom** [dabrowskiw/dabrowskiw.github.io#1]
I suggest to use the package `scrlayer-scrpage` in the latex template instead of the package `scrpage2`.

To do this, replace line 15 in the `bachelor.tex` file with the following line:

`\usepackage[automark]{scrlayer-scrpage}`

The package `scrpage2` is no longer present in the `texlive` installation. It can be installed later, but this makes it more difficult to use the template, especially if one does not have much experience with latex. At this point, I can't see any problems with package switching. The logfile shows no errors, the compilation works without problems.

A discussion on the top can be found here: https://tex.stackexchange.com/questions/541766/latex-error-file-scrpage2-sty-not-found

PS: I wanted to propose this in a PR, but I lack the permissions as far as I can tell.

**Comment by dabrowskiw** [comment]
Thanks a lot, very good catch, fixed with dabrowskiw/dabrowskiw.github.io@74981b5e
